include(FetchContent)

if(LAIR_BUILD_CLIENT_QT)
    find_package(Qt6 6.5 COMPONENTS Core Gui Widgets Network Sql Multimedia QUIET)
    if(Qt6_FOUND)
        message(STATUS "Found Qt6 for GUI client")
    else()
        message(STATUS "Qt6 not found yet. Configure CMAKE_PREFIX_PATH before enabling LAIR_BUILD_CLIENT_QT.")
    endif()
endif()

if(LAIR_ENABLE_SQLCIPHER)
    find_package(PkgConfig QUIET)
    if(PkgConfig_FOUND)
        pkg_check_modules(SQLCIPHER QUIET sqlcipher)
        if(SQLCIPHER_FOUND)
            add_library(SQLCipher::SQLCipher INTERFACE IMPORTED)
            target_include_directories(SQLCipher::SQLCipher INTERFACE ${SQLCIPHER_INCLUDE_DIRS})
            target_link_directories(SQLCipher::SQLCipher INTERFACE ${SQLCIPHER_LIBRARY_DIRS})
            target_link_libraries(SQLCipher::SQLCipher INTERFACE ${SQLCIPHER_LIBRARIES})
        endif()
    endif()
endif()

if(LAIR_ENABLE_SQLITE AND NOT TARGET SQLCipher::SQLCipher)
    find_package(SQLite3 QUIET)
    if(SQLite3_FOUND)
        message(STATUS "Found SQLite3")
    else()
        message(STATUS "SQLite3 not found. Persistence modules will stay scaffolded until installed.")
    endif()
endif()

if(LAIR_ENABLE_SODIUM)
    find_package(unofficial-sodium QUIET)
    if(unofficial-sodium_FOUND)
        message(STATUS "Found libsodium")
    else()
        message(STATUS "libsodium not found. Security modules will stay scaffolded until installed.")
    endif()
endif()

if(LAIR_ENABLE_OPUS)
    find_package(PkgConfig QUIET)
    if(PkgConfig_FOUND)
        pkg_check_modules(OPUS QUIET opus)
        if(OPUS_FOUND)
            add_library(Opus::opus INTERFACE IMPORTED)
            target_include_directories(Opus::opus INTERFACE ${OPUS_INCLUDE_DIRS})
            target_link_directories(Opus::opus INTERFACE ${OPUS_LIBRARY_DIRS})
            target_link_libraries(Opus::opus INTERFACE ${OPUS_LIBRARIES})
            message(STATUS "Found Opus")
        else()
            message(STATUS "Opus not found. Voice modules will stay scaffolded until installed.")
        endif()
    endif()
endif()

if(LAIR_ENABLE_LOGGING)
    find_package(spdlog CONFIG QUIET)
    if(spdlog_FOUND)
        message(STATUS "Found spdlog")
    else()
        message(STATUS "spdlog not found. Logging will use Com_Printf until installed.")
    endif()
endif()

